---
title: Randomodbuild
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: randomodbuild@protonmail.com
description: A log of all the weird stuff I do! Hopefully it is entertaining and/or
  helpful.
baseurl: ''
url: https://randomodbuild.github.io
twitter_username: randomodbuild
github_username: randomodbuild
permalink: "/:title/"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
